### ISSUE TITLE
连续的图片间隙无法消除

### ISSUE THREAD

**Issue by Lizhilin** [jin-yufeng/Parser#74]
```html
<div class="image-wrap"><img src="xxx.jpg"/></div>
<div class="image-wrap"><img src="xxx.jpg"/></div>
```
连续的图片会产生间隙 如何解决😡
设置内联block样式依旧无法解决~
trees.wxss 引入的样式如下：
```css
._img {
  vertical-align: top;
  margin: 0;
  padding: 0;
  display: block;
}
```

**Comment by jin-yufeng** [comment]
在 `trees.wxss` 里要这么写
```css
._img {
  display: block !important;
  font-size: 0;
}
```
这是因为 `img` 是通过 `rich-text` 显示的，需要给 `rich-text` 设置一个 `display`，在内联的 `style` 属性中没有 `display` 时，会被设置成 `inline-block`，所以要通过 `!important` 才能覆盖；另外 `._img` 只对 `rich-text` 生效（对内层的 `img` 无效），所以要通过 `font-size:0` 让内层的 `img` 的 `inline-block` 下的空隙消失，同时，`img` 绑定的 `class` 则只对内层的 `img` 有效，因为一个样式不能在内外层都生效，否则例如 `margin` 等样式会缩进两次；所以要有这两个样式才能让内外层的空隙都消失
还有很多别的方式可以实现（这样会让所有图片都变成 `display:block`）
- 设置内联样式
  ```html
  <img src="xxx" style="display:block">
  ```
- 加一个 `style` 标签
  ```javascript
  html = "<style>img{display:block}</style>"+html; // 也可以通过 class 匹配
  ```
- 设置 `tag-style` 属性
  ```html
  <parser tag-style="{{tagStyle}}" />
  ```
  ```javascript
  data:{
    tagStyle:{
      img: "display:block;" // 给 img 设置默认的 display:block 样式
    }
  }
  ```
